services:
  - type: web
    name: apple-review-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        fromDatabase:
          name: apple-review-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: apple-review-redis
          type: redis
          property: connectionString
      - key: RELOAD
        value: "false"
      - key: SCRAPER_BASE_URL
        value: "https://itunes.apple.com"
      - key: SCRAPER_DEFAULT_REVIEW_COUNT
        value: "100"
      - key: SCRAPER_MAX_REVIEW_COUNT
        value: "500"
      - key: BERT_MODEL_PATH
        value: "ml/artifacts/bert/bert-sentiment-v1"
      - key: BERT_MAX_LENGTH
        value: "128"

  - type: redis
    name: apple-review-redis
    plan: free
    ipAllowList: []

databases:
  - name: apple-review-db
    plan: free
